spring:
  application:
    name: "Location Service"
  datasource:
    password: fdproot
    tomcat:
      max-active: 50
      max-idle: 20
      max-wait: 20000
      min-idle: 15
    url: "jdbc:mysql://localhost:3306/fastdeliverypizza"
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      generate-ddl: true
      globally_quoted_identifiers: true
      idSeller:
        new_generator_mappings: false
  # RabbitMQ properties
  rabbitmq:
    host: localhost
    listener:
        default-requeue-rejected: false
endpoints:
  enabled: true
  sensitive: false

info:
  java:
    source: "${java.version}"

logging:
  level:
    root: INFO

management:
  info:
    build:
      enabled: true
    git:
      mode: full

server:
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
